name: Cats

on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "send_me_cats"
  send_me_cats:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: Action Cats
      uses: ruairidhwm/action-cats@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
