name: My Flaky Test

# on actions run the following jobs
on:
  # TODO 1: specify a branch

  # TODO 3: specify a cron schedule
  schedule:
    - cron: '*/1 * * * *'

jobs:
  # run the flaky test job
  flaky-tests:
    runs-on: ubuntu-latest
    # job recipe
    steps:
    # download repo
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # run tests repeatedly. If any of the pytests fail, then the step fails and so the job fails
    - name: Test with pytest repeatedly
      # TODO 2 fill in the step
      run: |
        for var in {1..100}; do pytest; done

  # TODO 4: add another job
  linkinator_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator@v1
        with:
          paths: README.md
